// react/todoapp/src/App.js
import logo from './logo.svg';
import './App.css';
import React, { useState, useRef, useEffect } from 'react'

function App() {
  
  //state
  const [todos, setTodos] = useState([]);

  //binding
  const todoText = useRef();

  //side effects
  useEffect(() => {
    const existingTodos = localStorage.getItem('todos');
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }, [])

  //events
  function addTodo(event) {
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next));
  }

  return (
    <div>
      <ul>
        {todos.map(todo => (<li key={todo}>{todo}</li>))}
      </ul>

      <form onSubmit={addTodo}>
        <input ref={todoText} />
        <input type="submit" value="add todo"/>
      </form>
    </div>
  );
}

export default App;

// solid/src/App.jsx
import logo from './logo.svg';
import styles from './App.module.css';
import { createSignal, onMount } from 'solid-js';
function App() {
  
  const [todos, setTodos] = createSignal([]);
  let todoText;

  onMount(() => {
    const existingTodos = localStorage.getItem('todos');
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  });

  function addTodo(event) {
    event.preventDefault();
    const next = [...todos(), todoText.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next));
  }

  return (
    <div>
      <ul>
        {todos().map(todo => (<li key={todo}>{todo}</li>))}
      </ul>

      <form onSubmit={addTodo}>
        <input type="text" ref={todoText}/>
        <input type="submit" value="add todo"/>
      </form>
    </div>
  );
}

export default App;
